### ISSUE TITLE
Add Travis-CI

### ISSUE THREAD

**Issue by danfiscus** [TheKing42/Pi-Lock#1]

**Comment by danfiscus** [comment]
Having trouble setting up Travis. For some reason it won't work because it's not one of my repositories, even though I'm an admin on this one. Help?

**Comment by ChristopherKing42** [comment]
There is nothing for Travis to do. We need code first.

**Comment by danfiscus** [comment]
But I don't think it's set up right still. I think it's linked to my fork not the original one?
